v1.1/Website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from . import db
from .models import User, Attendance, Profiles
from .auth import check_password_hash, generate_password_hash
import datetime
from datetime import datetime

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    username = current_user.username
    return render_template("home.html", user=current_user, username=username)



@views.route('/attendance', methods = ['GET', 'POST'])
@login_required
def attendance():
    received = request.form
    print(received)
    username = current_user.username
    data = Attendance.query.all()
    if request.method == 'POST':
        add_or_check = request.form.get('add_or_check')
        if add_or_check == 'check':
            input_id = request.form.get('employee_id')
            id_exist = Profiles.query.filter_by(id=input_id).first()
            if id_exist:
                msg = "Employee ID Found"
                now = datetime.now()
                name = id_exist.name
                date = now.strftime("%d-%m-%Y")
                time = now.strftime("%H:%M:%S")
                return render_template('add_attendance.html',user=current_user, employee_found=True, msg=msg, employee_id=input_id, name=name, date=date, time=time)
            else:
                flash("Employee ID NOT Found", category='error')
        elif add_or_check == 'add':
            id = request.form.get('employee_id')
            name = request.form.get('employee_name')
            date = request.form.get('date')
            time = request.form.get('time')
            status = request.form.get('status')
            new_attendance = Attendance(id=id, name=name, date=date, time=time, status=status)
            db.session.add(new_attendance)
            db.session.commit()
            flash('Added New Record of Attendance!', category='success')
            return redirect(url_for('views.attendance'))
        elif add_or_check == 'custom':
            id = request.form.get('employee_id')
            id_exist = Profiles.query.filter_by(id=id).first()
            if id_exist:
                name = id_exist.name
                date = request.form.get('date')
                day = date[8:10]
                month = date[5:7]
                year = date[0:4]
                date = day + "-" + month + "-" + year
                hour = request.form.get('hour')
                if len(hour) == 1:
                    hour = "0" + hour
                minute = request.form.get('minute')
                if len(minute) == 1:
                    minute = "0" + minute
                second = request.form.get('second')
                if len(second) == 1:
                    second = "0" + second
                time = hour + ":" + minute + ":" + second
                status = request.form.get('status')
                new_attendance = Attendance(id=id, name=name, date=date, time=time, status=status)
                db.session.add(new_attendance)
                db.session.commit()
                flash('Updated Attendance', category='success')
                return redirect(url_for('views.attendance'))
            else:
                flash('Employee ID Does NOT Exist', category='error')
                return redirect(url_for('views.attendance'))
        elif add_or_check == 'search':
            id = request.form.get('id')
            if not id:
                id = ""
            name = request.form.get('name')
            if not name:
                name = ""
            date = request.form.get('date')
            date_filter = ""
            if date:
                day = date[8:10]
                print(day)
                month = date[5:7]
                print(month)
                year = date[0:4]
                print(year)
                search_range = request.form.get('search_range')
                if search_range == 'year':
                    date_filter = year
                elif search_range == 'month':
                    date_filter = month + "-" + year
                elif search_range == 'day':
                    date_filter = day + "-" + month + "-" + year
            else:
                date = ""

            search_range = request.form.get('search_range')
            search_query = Attendance.query.filter(
                Attendance.id.like('%' + id + '%'),
                Attendance.name.like('%' + name + '%'),
                Attendance.date.like('%' + date_filter + '%')
            ).all()
            if not search_query:
                no_results = True
            return render_template('attendance.html', attendance=search_query, user=current_user, username=username, no_results=no_results)
    return render_template('attendance.html', attendance=data, user=current_user, username=username)

@views.route('/employee_list', methods =['GET', 'POST'])
@login_required
def employee_list():
    username = current_user.username
    data = Profiles.query.all()
    months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun' ,'Jul','Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    if request.method == 'POST':
        add_or_check = request.form.get('add_or_check')
        if add_or_check == 'search':
            id = request.form.get('id')
            if not id:
                id = ""
            name = request.form.get('name')
            if not name:
                name = ""
            gender = request.form.get('gender')
            if gender == 'Any':
                gender = ""
            date = request.form.get('date')
            date_filter = ""
            if date:
                day = date[8:10]
                print(day)
                month = date[5:7]
                print(month)
                year = date[0:4]
                print(year)
                search_range = request.form.get('search_range')
                if search_range == 'year':
                    date_filter = year
                elif search_range == 'month':
                    date_filter = month + "-" + year
                elif search_range == 'day':
                    date_filter = day + "-" + month + "-" + year
            else:
                date = ""
            age = request.form.get('age')
            if age == 'Any':
                age = ""
            department = request.form.get('department')
            if department == 'Any':
                department = ""
            search_range = request.form.get('search_range')
            search_query = Profiles.query.filter(
                Profiles.id.like('%' + id + '%'),
                Profiles.name.like('%' + name + '%'),
                Profiles.gender.like('%' + gender + '%'),
                Profiles.birthdate.like('%' + date_filter + '%'),
                Profiles.age.like('%' + age + '%'),
                Profiles.department.like('%' + department + '%')
            ).all()
            if not search_query:
                no_results = True
            else:
                no_results = False
            return render_template('employee_list.html', employees=search_query, user=current_user, username=username, no_results=no_results)
        else:
            id = request.form.get('employee_id')
            name = request.form.get('employee_name')
            department = request.form.get('employee_department')
            gender = request.form.get('employee_gender')
            id_exists = Profiles.query.filter_by(id=id).first()
            if id_exists:
                flash('Employee already exist with current ID.', category='error')
            elif len(id) < 14:
                flash('Invalid Format for ID.', category='error')
            else:
                currentyear = datetime.now().strftime("%Y")
                sliced_currentyear = int(currentyear[2:4])
                birthyear = id[0:2]
                if sliced_currentyear - int(birthyear) < 0:
                    birthyear = "19" + str(birthyear)
                else:
                    birthyear = currentyear[0:2] + str(birthyear)
                age = int(currentyear) - int(birthyear)
                birthmonth = months[int(id[2:4])-1]
                birthdate = id[4:6] + "/" + birthmonth + "/" + birthyear
                new_employee = Profiles(id=id, name=name,department=department, gender=gender, age=age, birthdate=birthdate)
                db.session.add(new_employee)
                db.session.commit()
                flash('Successfully Added New Employee.', category='success')
                return redirect(url_for('views.employee_list'))
    return render_template('employee_list.html', employees=data, user=current_user, username=username)

@views.route('/account_settings', methods = ['GET', 'POST'])
@login_required
def account_settings():
    username = current_user.username
    name = current_user.name
    email = current_user.email
    password = current_user.password
    return render_template('account_settings.html', user=current_user, username=username, name=name, email=email, password=password)

@views.route('/change_password', methods = ['GET', 'POST'])
@login_required
def change_password():
    username = current_user.username
    if request.method == 'POST':
        current_password = request.form.get('current_password')
        new_password1 = request.form.get('new_password1')
        new_password2 = request.form.get('new_password2')
        userpasswordhash = current_user.password
        if not check_password_hash(userpasswordhash, current_password):
            flash('Password Incorrect',category='error')
        elif len(new_password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        elif new_password1 != new_password2:
            flash("New passwords don't match.",category='error')
        else:
            current_user.password = generate_password_hash(new_password1,method='SHA256')
            db.session.commit()

v1.1/Website/templates/account_settings.html
{% extends "base.html" %}

{% block content %}
<h3 align="center">Account Settings</h3>

<form method="POST">
    <div class="form-group row">
        <label for="username" class="col-sm-2 col-form-label">Username</label>
        <div class="mb-2 mr-sm-2">
        <input
            type="text"
            readonly
            class="form-control"
            id="username"
            name="username"
            value="{{ username }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="mb-2 mr-sm-2">
        <input
            type="text"
            readonly
            class="form-control"
            id="name"
            name="name"
            value="{{ name }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="email" class="col-sm-2 col-form-label">Email</label>
        <div class="mb-2 mr-sm-2">
        <input
            type="text"
            readonly
            class="form-control"
            id="email"
            name="email"
            value="{{ email }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="password" class="col-sm-2 col-form-label">Password</label>
        <div class="mb-2 mr-sm-2">
        <input
            type="password"
            readonly
            class="form-control"
            id="password"
            name="password"
            value="1234567890">
        </div>
        <a class="btn btn-primary col-sm-1.5" href="{{ url_for('views.change_password') }}">Change Password</a>
    </div>

    <br />

</form>
{% endblock %}

v1.1/Website/templates/add_attendance.html
{% extends "base.html" %}

{% block content %}

<form action="{{ url_for('views.attendance') }}" method="POST">
    <h3 align="center">Add Attendance</h3>
    <h4>Please confirm with the details below:</h4>
    <div class="form-group">
        <input type="hidden" class="form-control" id="add_or_check" name="add_or_check" value="add">
    </div>
    <div class="form-group">
        <label for="employee_id">Employee ID: </label>
        <input
            type="text"
            class="form-control"
            id="employee_id"
            name="employee_id"
            value="{{ employee_id }}"
            >
    </div>
    <div class="form-group">
        <label for="name">Name: </label>
        <input
            type="text"
            class="form-control"
            id="employee_name"
            name="employee_name"
            value="{{ name }}"
            >
    </div>
    <div class="form-group">
        <label for="date">Current Date: </label>
        <input
            type="text"
            class="form-control"
            id="date"
            name="date"
            value="{{ date }}"
            >
    </div>
    <div class="form-group">
        <label for="time">Time: </label>
        <input
            type="text"
            class="form-control"
            id="time"
            name="time"
            value="{{ time }}"
            >
    </div>
    <div class="form-group">
        <label for="status">Status: </label>
        <div class="form-check form-check-inline">
            <input
                type="radio"
                class="form-check-input"
                name="status"
                id="status"
                value="IN"
                checked>
            <label class="form-check-label" for="status">IN</label>
        </div>
        <div class="form-check form-check-inline">
            <input
                type="radio"
                class="form-check-input"
                name="status"
                id="status"
                value="OUT">
            <label class="form-check-label" for="status">OUT</label>
        </div>
    </div>
    <div class="form-group">
    <br />
    <button type="submit" class="btn btn-primary">Confirm</button>
    </div>
</form>
{% endblock %}

v1.1/Website/templates/attendance.html
{% extends "base.html" %}

{% block content %}

<div id="selector" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Attendance</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="signtype">How would you like to add the attendance?</label>
                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-success" data-toggle="modal" href="#easy">Attendance NOW</button>
                    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#custom">Attendance CUSTOM</button>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div id="easy" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Easy Attendance</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="signtype">Enter the ID of employee to take attendance.</label>
                </div>
                <form action="{{ url_for('views.attendance') }}" class="form-inline" method="POST">
                    <div class="form-group col-md-12">
                        <label for="employee_id">ID: </label>
                        <input type="hidden" class="form-control" id="add_or_check" name="add_or_check" value="check">
                        <input type="text" class="form-control" id="employee_id" name="employee_id" placeholder="NRIC..">
                        <button
                                type="submit"
                                name="submit"
                                class="btn btn-dark"
                                data-toggle="modal"
                                data-target="#checkid"
                        >Submit</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div id="custom" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Custom Attendance</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="signtype">Enter the following details accordingly.</label>
                </div>
                <form action="{{ url_for('views.attendance') }}" method="POST">
                    <div class="form-group">
                        <label for="employee_id">Employee ID: </label>
                        <input type="hidden" class="form-control" id="add_or_check" name="add_or_check" value="custom">
                        <input
                            type="text"
                            class="form-control"
                            id="employee_id"
                            name="employee_id"
                            placeholder="Must be Exisiting Employee ID"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="date">Custom Date: </label>
                        <input
                            type="date"
                            class="form-control"
                            name="date"
                            required>
                    </div>
                    <div class="form-inline">
                        <div class="form-group">
                            <label for="hour">Custom Time: </label>
                            <select
                                class="form-control"
                                name="minute"
                                required>
                                {% for i in range(0,24) %}
                                    <option>{{ i }}</option>
                                {% endfor %}
                            </select>
                            <label> : </label>
                        </div>
                        <div class="form-group">
                            <select
                                class="form-control"
                                name="hour"
                                required>
                                {% for i in range(0,60) %}
                                    <option>{{ i }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label> : </label>
                            <select
                                class="form-control"
                                name="second"
                                required>
                                {% for i in range(0,60) %}
                                    <option>{{ i }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="status">Status: </label><div class="form-check form-check-inline">
                            <input
                                type="radio"
                                class="form-check-input"
                                name="status"
                                id="status"
                                value="IN"
                                checked>
                            <label class="form-check-label" for="status">IN</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input
                                type="radio"
                                class="form-check-input"
                                name="status"
                                id="status"
                                value="OUT">
                            <label class="form-check-label" for="status">OUT</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <button
                                type="submit"
                                name="submit"
                                class="btn btn-dark"
                        >Submit</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% if employee_found %}
{% endif %}

<div id="filter" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Filter</h4>
            </div>
            <div class="modal-body">
                <form method="POST">
                    <div class="container">
                        <div class="row">
                            <label>Edit the filter to your own preferences.</label>
                            <input
                                type="hidden"
                                name="add_or_check"
                                value="search">
                        </div>
                        <div class="row">
                            <label class="col-sm-2">ID: </label>
                            <input
                                type="text"
                                class="col-sm-6"
                                name="id">
                        </div>
                        <div class="row">
                            <label class="col-sm-2">Name: </label>
                            <input
                                type="text"
                                class="col-sm-6"
                                name="name">
                        </div>
                        <div class="row">
                            <label class="col-sm-2">Date: </label>
                            <input
                                class="col-sm-6"
                                name="date"
                                type="date">
                            </input>
                        </div>
                        <label class="form-check form-check-inline">Precise: </label>
                        <div class="form-check form-check-inline">
                            <input
                                type="radio"
                                class="form-check-input"
                                name="search_range"
                                id="search_range"
                                value="day"
                                checked>
                            <label class="form-check-label" for="search_range">Day</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input
                                type="radio"
                                class="form-check-input"
                                name="search_range"
                                id="search_range"
                                value="month">
                            <label class="form-check-label" for="search_range">Month</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input
                                type="radio"
                                class="form-check-input"
                                name="search_range"
                                id="search_range"
                                value="year"
                                value="year">
                            <label class="form-check-label" for="search_range">Year</label>
                        </div>
                        <div class="row justify-content-md-center">
                            <button type="submit" class="btn btn-dark col-md-2">Search</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a type="button" class="btn btn-dark" id="back_to_attendance" href="/attendance">Clear Filters</a>
                <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

    <div class="row">
        <h2 class="col-md-6">Attendance Log</h2>
            <div class="pull-right col-md-6">
                <button style="float:right" type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#filter">Edit Filters</button>
                <button style="float:right" type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#selector">Add Attendance</button>
            </div>
    </div>
  <table class="table table-stripped">
    <thead class="thead-dark">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Date (DD/MM/YY)</th>
          <th>Time (hh:mm:ss)</th>
          <th>Status</th>
        </tr>

        {% for row in attendance %}
        <tr>
            <td>{{row.id}}</td>
            <td>{{row.name}}</td>
            <td>{{row.date}}</td>
            <td>{{row.time}}</td>
            <td>{{row.status}}</td>
          {% endfor %}
        </tr>
    </thead>
  </table>
{% if no_results %}
    <h3 align="center">No Results Found.</h3>
{% endif %}
{% endblock %}

v1.1/Website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="{{url_for('static', filename = 'favicon_xnet.jpg' )}}" type="image/jpg"/>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}X Net{% endblock %}</title>
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">X Net</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
                  <li class="nav-item active">
                      <a class="nav-item nav-link" id="home" href="/">Home</a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-item nav-link" id="attendance" href="/attendance">Attendance</a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-item nav-link" id="employee_list" href="/employee_list">Employees</a>
                  </li>
              {% else %}
                  <li class="nav-item active">
                      <a class="nav-item nav-link" id="login" href="/login">Login</a>
                  </li>
              {% endif %}
              </ul>
              {% if user.is_authenticated %}
              <div class="nav-item dropdown">
                <button class="nav-link dropdown-toggle btn btn-dark" style="color: white;" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ username }}</button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown03">
                    {% if username == 'admin' %}
                        <a class="dropdown-item" id="sign_up" href="/sign_up">Register</a>
                    {% endif %}
                    <a class="dropdown-item" href="/account_settings">Account Settings</a>
                    <a class="dropdown-item" id="logout" href="/logout">Logout</a>
                </div>
              </div>
              {% endif %}
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <br>
            {% for category, message in messages %}
                {% if category == 'error' %}
                <div class="alert alert-danger alter-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% else %}
                <div class="alert alert-success alter-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <br>
    <br>
    <br>
    <div class="header" align="center">
        <h1 style="display: inline;">
            <img
                    width="100"
                    length="100"
                    src="{{url_for('static', filename = 'favicon_xnet.jpg')}}"
                    alt="logo"/>
            X Net </h1>
        <h4 style="display: inline;">Database</h4>
    </div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
</body>
</html>

v1.1/Website/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1 align="center">Welcome to X Net</h1>
<h2 align="center">{{ username }}</h2>
{% endblock %}

v1.1/Website/templates/login.html
{% extends "base.html" %}

{% block content %}

<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="username">Username</label>
        <input
            type="text"
            class="form-control"
            id="username"
            name="username"
            placeholder="Enter Username">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter Password">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}